FROM node:20-alpine AS builder
WORKDIR /app
COPY server/package*.json ./
RUN npm ci
COPY server/ .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY server/src/db/*.csv ./dist/db/
COPY server/package*.json ./
RUN npm ci --production
EXPOSE 3001
CMD ["node", "dist/index.js"]